
language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.3
env:
  - MIX_ENV=test
otp_release:
  - 19.3
  - 20.3
  - 21.0
cache:
  directories:
    - _build
    - deps
before_script:
  - mix compile
  - travis_wait mix dialyzer --plt
script:
  - mix coveralls.travis
  - mix dialyzer --halt-exit-status
matrix:
  exclude:
    - elixir: 1.4.5
      otp_release: 21.0
    - elixir: 1.5.3
      otp_release: 21.0
